### PR TITLE
Update to netcoreapp3.1

### PR DESCRIPTION
**Pull request by emgarten**
* Update Hexastore.Web and test project to netcoreapp3.0
* Move Hexastore and Hexastore.Rocks to netstandard2.1
* Update docker file for netcoreapp3.0
* NuGet dependency clean up and updates
* Added Microsoft.CSharp dependency to fix build errors after moving to netstandard2.1

### CODE REVIEW

**Comment by emgarten** [comment]
Hexastore had the same JObject.FromObject error with both netstandard2.1 and netcoreapp3.0, the types it was missing are in the Microsoft.CSharp package.

As netstandard Hexastore and Hexastore.Rocks could become their own packages and used outside of the web app.

**Comment by emgarten** [comment]
netcoreapp3.1 is out today, I've updated the PR. 🎉 

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/

**Comment by jobeland** [comment]
LGTM :shipit:

**Comment by emgarten** [comment]
I'll create a new PR for this

**Pull request closed without merging**
